version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  claim-service:
    image: carinsurance-claim-service
    container_name: claim-service
    depends_on:
      - mongo
    environment:
      - MongoSettings__ConnectionString=mongodb://admin:admin123@mongo:27017

  policy-service:
    image: carinsurance-policy-service
    container_name: policy-service
    depends_on:
      - mongo
    environment:
      - MongoSettings__ConnectionString=mongodb://admin:admin123@mongo:27017
