version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  claim-service:
    image: carinsurance-claim-service
    container_name: claim-service
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  policy-service:
    image: carinsurance-policy-service
    container_name: policy-service
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
